version: '3.4'

services:
  downloadfilefromfilesystemwebapplication:
    image: ${DOCKER_REGISTRY-}downloadfilefromfilesystemwebapplication
    build:
      context: .
      dockerfile: DownloadFileFromFileSystemWebApplication/Dockerfile
